app/projects/modernisation_platform/routes/main.py
import logging
from flask import Blueprint, render_template, jsonify
from app.projects.modernisation_platform.services.service import get_all_json_data, get_readme_incident_info, get_collaborators_data, get_failed_workflow_runs, get_all_workflow_runs
from datetime import datetime, timedelta
from collections import defaultdict

from app.shared.middleware.auth import requires_auth

logger = logging.getLogger(__name__)

modernisation_platform_main = Blueprint("modernisation_platform_main", __name__)

@modernisation_platform_main.route("/", methods=["GET", "POST"])
@requires_auth
def index():
    return render_template("projects/modernisation_platform/pages/home.html")

@modernisation_platform_main.route("/sandbox-summary")
@requires_auth
def sandbox_summary():
    org = "ministryofjustice"
    repo = "modernisation-platform"
    branch = "main"
    directory = "environments"
    data = get_all_json_data(org, repo, branch, directory)
    result = []
    seen = set()
    for app in data:
        for env in app.get("environments", []):
            sandbox_groups = [
                access.get("sso_group_name", "")
                for access in env.get("access", [])
                if access.get("level") == "sandbox"
            ]
            if sandbox_groups:
                key = (app["_filename"], env["name"])
                if key not in seen:
                    seen.add(key)
                    nuke_status = env.get("nuke", "")
                    if env["name"].lower() == "test":
                        nuke_status = "exclude"
                    elif nuke_status not in ["exclude", "rebuild"]:
                        nuke_status = "include"
                    result.append({
                        "app_name": app["_filename"],
                        "environment": env["name"],
                        "nuke": nuke_status,
                        "groups": sandbox_groups
                    })
    return render_template("projects/modernisation_platform/pages/sandbox_summary.html", apps=result)

@modernisation_platform_main.route("/platform-access-summary")
@requires_auth
def platform_access_summary():
    org = "ministryofjustice"
    repo = "modernisation-platform"
    branch = "main"
    directory = "environments"
    data = get_all_json_data(org, repo, branch, directory)
    
    # Track role counts and collect access items grouped by app
    role_counts = {}
    app_access_map = {}  # Map of app_name -> dict of (env, access_level) -> list of groups
    seen_role_counts = set()  # Track unique (app, env, role) for counting
    
    for app in data:
        app_name = app["_filename"]
        if app_name not in app_access_map:
            app_access_map[app_name] = {}
        
        for env in app.get("environments", []):
            for access in env.get("access", []):
                access_level = access.get("level", "")
                sso_group = access.get("sso_group_name", "")
                
                # Count unique roles per app/env combination (not per team)
                if access_level:
                    count_key = (app_name, env["name"], access_level)
                    if count_key not in seen_role_counts:
                        seen_role_counts.add(count_key)
                        role_counts[access_level] = role_counts.get(access_level, 0) + 1
                
                # Group access details by environment and access level
                if access_level and sso_group:
                    key = (env["name"], access_level)
                    if key not in app_access_map[app_name]:
                        app_access_map[app_name][key] = []
                    
                    # Generate link - Azure groups go to Azure portal, others to GitHub
                    if "azure" in sso_group.lower():
                        group_url = "https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupsManagementMenuBlade/~/AllGroups"
                    else:
                        group_url = f"https://github.com/orgs/ministryofjustice/teams/{sso_group}"
                    
                    app_access_map[app_name][key].append({
                        "group_name": sso_group,
                        "group_url": group_url
                    })
    
    # Define environment order for sorting
    def env_sort_key(item):
        env_name = item[0][0].lower()  # First element of tuple (environment, access_level)
        order = {"development": 0, "dev": 0, "test": 1, "preproduction": 2, "pre-production": 2, "preprod": 2, "production": 3}
        return (order.get(env_name, 999), env_name)  # Unknown environments go last, then alphabetically
    
    # Convert map to list of apps with their access details
    access_items = []
    for app_name in sorted(app_access_map.keys()):
        if app_access_map[app_name]:  # Only include apps with access
            access_details = []
            for (environment, access_level), groups in sorted(app_access_map[app_name].items(), key=env_sort_key):
                access_details.append({
                    "environment": environment,
                    "access_level": access_level,
                    "groups": groups
                })
            
            access_items.append({
                "app_name": app_name,
                "access_details": access_details
            })
    
    # Sort role counts by count (descending) for better display
    role_counts = dict(sorted(role_counts.items(), key=lambda x: x[1], reverse=True))
    
    return render_template(
        "projects/modernisation_platform/pages/platform_access_summary.html",
        role_counts=role_counts,
        access_items=access_items
    )

@modernisation_platform_main.route("/platform-contact-details")
@requires_auth
def platform_contact_details():
    org = "ministryofjustice"
    repo = "modernisation-platform"
    branch = "main"
    directory = "environments"
    data = get_all_json_data(org, repo, branch, directory)
    
    apps = []
    app_names = []
    
    for app in data:
        app_name = app["_filename"]
        app_names.append(app_name)
        
        # Get tags
        tags = app.get("tags", {})
        business_unit = tags.get("business-unit", "N/A")
        contact_email = tags.get("infrastructure-support", "N/A")
        slack_channel = tags.get("slack-channel", "N/A")
        
        apps.append({
            "app_name": app_name,
            "business_unit": business_unit,
            "contact_email": contact_email,
            "slack_channel": slack_channel
        })
    
    # Fetch incident info from READMEs
    readme_org = "ministryofjustice"
    readme_repo = "modernisation-platform-environments"
    readme_branch = "main"
    incident_info = get_readme_incident_info(readme_org, readme_repo, readme_branch, app_names)
    
    # Add incident info to apps
    for app in apps:
        app_name = app["app_name"]
        if app_name in incident_info:
            app["incident_hours"] = incident_info[app_name].get("incident_hours", "N/A")
            app["incident_contact"] = incident_info[app_name].get("incident_contact", "N/A")
        else:
            app["incident_hours"] = "N/A"
            app["incident_contact"] = "N/A"
    
    return render_template(
        "projects/modernisation_platform/pages/platform_contact_details.html",
        apps=apps
    )

@modernisation_platform_main.route("/collaborators-summary")
@requires_auth
def collaborators_summary():
    org = "ministryofjustice"
    repo = "modernisation-platform"
    branch = "main"
    
    data = get_collaborators_data(org, repo, branch)
    users = data.get("users", [])
    
    # Process collaborators data
    collaborators = []
    env_counts = {}
    
    for user in users:
        username = user.get("username", "")
        github_username = user.get("github-username", "N/A")
        accounts = user.get("accounts", [])
        line_number = user.get("_line_number", 1)
        
        # Get environment-role pairs
        env_role_pairs = []
        for account in accounts:
            account_name = account.get("account-name", "")
            access = account.get("access", "")
            
            if account_name:
                env_role_pairs.append({
                    "environment": account_name,
                    "role": access if access else "N/A"
                })
                
                # Count environments
                env_counts[account_name] = env_counts.get(account_name, 0) + 1
        
        # Generate GitHub link to the exact line
        github_file_url = f"https://github.com/{org}/{repo}/blob/{branch}/collaborators.json#L{line_number}"
        
        collaborators.append({
            "username": username,
            "github_username": github_username,
            "env_role_pairs": env_role_pairs,
            "json_link": github_file_url
        })
    
    # Sort environment counts for pie chart
    env_counts_sorted = dict(sorted(env_counts.items(), key=lambda x: x[1], reverse=True)[:10])  # Top 10
    
    return render_template(
        "projects/modernisation_platform/pages/collaborators_summary.html",
        collaborators=collaborators,
        total_collaborators=len(collaborators),
        env_counts=env_counts_sorted
    )

@modernisation_platform_main.route("/workflow-failures")
@requires_auth
def workflow_failures():
    from flask import request
    
    org = "ministryofjustice"
    repo = "modernisation-platform"
    branch = "main"
    
    # Get time range from query parameter, default to 24 hours
    time_range = request.args.get('time_range', '24h')
    
    # Convert time range to hours
    time_range_map = {
        '24h': (24, 'Last 24 hours'),
        '48h': (48, 'Last 48 hours'),
        '7d': (7 * 24, 'Last 7 days'),
        '14d': (14 * 24, 'Last 14 days'),
        '30d': (30 * 24, 'Last 30 days')
    }
    

app/templates/projects/modernisation_platform/pages/collaborators_summary.html
{% extends "shared/components/base.html" %}

{% block pageTitle %}
   Collaborators Summary
{% endblock %}

{% block content %}
<h1 class="govuk-heading-l">Collaborators Summary</h1>
  <p class="govuk-body">
    This page details individual collaborators with direct access to Modernisation Platform environments.<br><br>
    <i>Collaborators</i> are users who are external to the organisation who have been granted access to MoJ AWS environments and GitHub repositories.<br><br>
    For more information on collaborators and access management, please refer to our <a class="govuk-link" href="https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/working-as-a-collaborator.html">documentation</a>.
  </p>

  <section class="govuk-summary-list govuk-!-margin-bottom-6">
    <h2 class="govuk-heading-m">Summary</h2>
    <div class="govuk-summary-list__row">
      <dt class="govuk-summary-list__key">Total Collaborators</dt>
      <dd class="govuk-summary-list__value">{{ total_collaborators }}</dd>
    </div>
  </section>

  <!-- Chart Section -->
  <section class="govuk-!-margin-bottom-6">
    <h2 class="govuk-heading-m">Top 10 Environments by Collaborator Count</h2>
    <p class="govuk-body-s">Showing the environments with the most individual collaborators.</p>
    <div style="max-width: 800px; margin: 0 auto;">
      <canvas id="envCollaboratorsChart"></canvas>
    </div>
  </section>

  <section>
    <h2 class="govuk-heading-m">All Collaborators</h2>

    <input type="text" id="collaborator-search" class="govuk-input" placeholder="Search username, github username, environment, role..." style="margin-bottom: 1em;">
    <table class="govuk-table">
      <thead>
        <tr>
          <th class="govuk-table__header">Username</th>
          <th class="govuk-table__header">GitHub Username</th>
          <th class="govuk-table__header">Environment</th>
          <th class="govuk-table__header">Role</th>
        </tr>
      </thead>
      <tbody id="collaborator-table-body">
        {% for collaborator in collaborators %}
          {% if collaborator.env_role_pairs|length > 0 %}
            {% for pair in collaborator.env_role_pairs %}
        <tr>
          {% if loop.first %}
          <td class="govuk-table__cell" rowspan="{{ collaborator.env_role_pairs|length }}">
            <a class="govuk-link" href="{{ collaborator.json_link }}" target="_blank" rel="noopener noreferrer">{{ collaborator.username }}</a>
          </td>
          <td class="govuk-table__cell" rowspan="{{ collaborator.env_role_pairs|length }}">
            {% if collaborator.github_username != 'N/A' and collaborator.github_username != 'no-value-supplied' %}
              <a class="govuk-link" href="https://github.com/{{ collaborator.github_username }}" target="_blank" rel="noopener noreferrer">{{ collaborator.github_username }}</a>
            {% else %}
              {{ collaborator.github_username }}
            {% endif %}
          </td>
          {% endif %}
          <td class="govuk-table__cell">{{ pair.environment }}</td>
          <td class="govuk-table__cell">{{ pair.role }}</td>
        </tr>
            {% endfor %}
          {% else %}
        <tr>
          <td class="govuk-table__cell">
            <a class="govuk-link" href="{{ collaborator.json_link }}" target="_blank" rel="noopener noreferrer">{{ collaborator.username }}</a>
          </td>
          <td class="govuk-table__cell">
            {% if collaborator.github_username != 'N/A' and collaborator.github_username != 'no-value-supplied' %}
              <a class="govuk-link" href="https://github.com/{{ collaborator.github_username }}" target="_blank" rel="noopener noreferrer">{{ collaborator.github_username }}</a>
            {% else %}
              {{ collaborator.github_username }}
            {% endif %}
          </td>
          <td class="govuk-table__cell" colspan="2">No environments</td>
        </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </section>

  <!-- Chart.js Library -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
  
  <script>
    // Search functionality - filter individual rows and adjust rowspan
    document.getElementById('collaborator-search').addEventListener('input', function() {
      const query = this.value.toLowerCase().trim();
      const terms = query.split(/\s+/);
      const rows = document.querySelectorAll('#collaborator-table-body tr');
      
      let currentUserRows = [];
      let currentUsername = null;
      let currentGithubUsername = null;
      let currentJsonLink = null;
      
      rows.forEach((row) => {
        // Check if this row has username cell (first row of a user group)
        const hasUsername = row.cells[0].hasAttribute('rowspan');
        
        if (hasUsername) {
          // Process previous user group
          if (currentUserRows.length > 0) {
            processUserGroup(currentUserRows, currentUsername, currentGithubUsername, currentJsonLink);
          }
          
          // Start new user group - store username info
          currentUsername = row.cells[0].cloneNode(true);
          currentGithubUsername = row.cells[1].cloneNode(true);
          currentJsonLink = row.cells[0].querySelector('a')?.href || '';
          currentUserRows = [row];
        } else {
          // This is a continuation row for the same user
          currentUserRows.push(row);
        }
      });
      
      // Process last user group
      if (currentUserRows.length > 0) {
        processUserGroup(currentUserRows, currentUsername, currentGithubUsername, currentJsonLink);
      }
      
      function processUserGroup(userRows, usernameCell, githubUsernameCell, jsonLink) {
        // Get username text for matching
        const username = usernameCell.textContent.toLowerCase();
        const githubUsername = githubUsernameCell.textContent.toLowerCase();
        
        // Check if username/github username matches any search term
        const usernameMatches = terms.some(term => 
          username.includes(term) || githubUsername.includes(term)
        );
        
        if (usernameMatches) {
          // If username matches, show all rows for this user
          userRows.forEach(r => r.style.display = '');
          
          // Ensure first row has correct rowspan
          const firstRow = userRows[0];
          if (firstRow.cells[0].hasAttribute('rowspan')) {
            firstRow.cells[0].setAttribute('rowspan', userRows.length);
            firstRow.cells[1].setAttribute('rowspan', userRows.length);
          }
        } else {
          // Username doesn't match, check which individual rows match (env/role search)
          const matchingRows = userRows.filter(row => {
            const text = Array.from(row.cells).map(cell => cell.textContent.toLowerCase()).join(' ');
            return terms.every(term => text.includes(term));
          });
          
          if (matchingRows.length === 0) {
            // Hide all rows for this user
            userRows.forEach(r => r.style.display = 'none');
          } else {
            // Show only matching rows
            userRows.forEach(r => r.style.display = 'none');
            matchingRows.forEach(r => r.style.display = '');
            
            // Update the first visible row to have the username cells with correct rowspan
            const firstVisibleRow = matchingRows[0];
            
            // Remove old username cells if they exist
            if (firstVisibleRow.cells[0].hasAttribute('rowspan')) {
              // Already has username cells, just update rowspan
              firstVisibleRow.cells[0].setAttribute('rowspan', matchingRows.length);
              firstVisibleRow.cells[1].setAttribute('rowspan', matchingRows.length);
            } else {
              // Need to add username cells
              const newUsernameCell = usernameCell.cloneNode(true);
              const newGithubCell = githubUsernameCell.cloneNode(true);
              newUsernameCell.setAttribute('rowspan', matchingRows.length);
              newGithubCell.setAttribute('rowspan', matchingRows.length);
              firstVisibleRow.insertBefore(newGithubCell, firstVisibleRow.firstChild);
              firstVisibleRow.insertBefore(newUsernameCell, firstVisibleRow.firstChild);
            }
          }
        }
      }
    });

    // Chart.js visualization
    const ctx = document.getElementById('envCollaboratorsChart').getContext('2d');
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: {{ env_counts.keys() | list | tojson }},
        datasets: [{
          label: 'Number of Collaborators',
          data: {{ env_counts.values() | list | tojson }},
          backgroundColor: '#1d70b8', // GOV.UK blue
          borderColor: '#003078',
          borderWidth: 1
        }]
      },
      options: {
        responsive: true,
        maintainAspectRatio: true,
        indexAxis: 'y', // This makes it horizontal
        plugins: {
          legend: {
            display: false
          },
          title: {
            display: false
          }
        },
        scales: {
          x: {
            beginAtZero: true,
            ticks: {
              stepSize: 1
            },
            title: {
              display: true,
              text: 'Number of Collaborators'
            }
          },
          y: {
            title: {
              display: true,
              text: 'Environment'
            }
          }
        }
      }
    });
  </script>
  
  {% endblock %}

app/templates/projects/modernisation_platform/pages/home.html
{% extends "shared/components/base.html" %}

{% block pageTitle %}
   Modernisation Platform
{% endblock %}

{% block content %}

  {{ govukBreadcrumbs({
      "items": [
        {
          "text": "Home",
          "href": "/"
        },
        {
          "text": "Modernisation Platform"
        }
      ]
    }) }}

  <h1 class="govuk-heading-xl">Modernisation Platform Overview</h1>

  <section>
    <h2 class="govuk-heading-m">Reports</h2>
    <p class="govuk-body-s">View platform access reports for users and teams in the Modernisation Platform.</p>
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-one-third">
        <h3 class="govuk-heading-s govuk-!-margin-bottom-1">
          <a class="govuk-link" href="{{ url_for('modernisation_platform_main.platform_environments_summary') }}">Environments Summary</a>
        </h3>
        <p class="govuk-body-s">Dashboard view of key platform statistics and metrics.</p>
      </div>
      <div class="govuk-grid-column-one-third">
        <h3 class="govuk-heading-s govuk-!-margin-bottom-1">
          <a class="govuk-link" href="{{ url_for('modernisation_platform_main.platform_access_summary') }}">Access Summary</a>
        </h3>
        <p class="govuk-body-s">View all access roles and their usage across environments.</p>
      </div>
      <div class="govuk-grid-column-one-third">
        <h3 class="govuk-heading-s govuk-!-margin-bottom-1">
          <a class="govuk-link" href="{{ url_for('modernisation_platform_main.sandbox_summary') }}">Sandbox Access Summary</a>
        </h3>
        <p class="govuk-body-s">See a summary of sandbox access for Modernisation Platform users.</p>
      </div>
    </div>
    <div class="govuk-grid-row govuk-!-margin-top-3">
      <div class="govuk-grid-column-one-third">
        <h3 class="govuk-heading-s govuk-!-margin-bottom-1">
          <a class="govuk-link" href="{{ url_for('modernisation_platform_main.platform_contact_details') }}">Contact Details</a>
        </h3>
        <p class="govuk-body-s">View contact information for all platform applications.</p>
      </div>
      <div class="govuk-grid-column-one-third">
        <h3 class="govuk-heading-s govuk-!-margin-bottom-1">
          <a class="govuk-link" href="{{ url_for('modernisation_platform_main.collaborators_summary') }}">Collaborators Summary</a>
        </h3>
        <p class="govuk-body-s">View individual collaborators and their environment access.</p>
      </div>
    </div>
    <div class="govuk-grid-row govuk-!-margin-top-3">
      <div class="govuk-grid-column-one-third">
        <h3 class="govuk-heading-s govuk-!-margin-bottom-1">
          <a class="govuk-link" href="{{ url_for('modernisation_platform_main.workflow_failures') }}">Workflow Failures</a>
        </h3>
        <p class="govuk-body-s">View failed GitHub Actions workflows with customizable time ranges.</p>
      </div>
    </div>
  </section>

{% endblock %}

app/templates/projects/modernisation_platform/pages/platform_access_summary.html
{% extends "shared/components/base.html" %}

{% block pageTitle %}
   Platform Access Summary
{% endblock %}

{% block content %}
<h1 class="govuk-heading-l">Platform Access Summary</h1>
  <p class="govuk-body">
    This page details all access roles being used across Modernisation Platform environments.
  </p>
  <p class="govuk-body">
    Consult our <a class="govuk-link" href="https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/platform-user-roles.html">documentation</a> for more information on platform user roles.
  </p>

  <!-- Chart Section -->
  <section class="govuk-!-margin-bottom-6">
    <h2 class="govuk-heading-m">Access Role Usage</h2>
    <p class="govuk-body-s">Each count represents one role assigned to one environment, regardless of how many teams have that role.</p>
    <div style="max-width: 800px; margin: 0 auto;">
      <canvas id="roleUsageChart"></canvas>
    </div>
  </section>

  <!-- Text Summary (kept for accessibility) -->
  <details class="govuk-details">
    <summary class="govuk-details__summary">
      <span class="govuk-details__summary-text">View detailed role counts</span>
    </summary>
    <div class="govuk-details__text">
      <dl class="govuk-summary-list">
        {% for role, count in role_counts.items() %}
        <div class="govuk-summary-list__row">
          <dt class="govuk-summary-list__key">{{ role }}</dt>
          <dd class="govuk-summary-list__value">{{ count }}</dd>
        </div>
        {% endfor %}
      </dl>
    </div>
  </details>

  <section>
    <h2 class="govuk-heading-m">All Environments and Access</h2>

    <input type="text" id="access-search" class="govuk-input" placeholder="Search apps, environments, group name, access level..." style="margin-bottom: 1em;">
    <table class="govuk-table">
      <thead>
        <tr>
          <th class="govuk-table__header">App Name</th>
          <th class="govuk-table__header">Environment</th>
          <th class="govuk-table__header">Access Level</th>
          <th class="govuk-table__header">Group Name(s)</th>
        </tr>
      </thead>
      <tbody id="access-table-body">
        {% for item in access_items %}
          {% if item.access_details|length > 0 %}
            {% for detail in item.access_details %}
        <tr data-app-name="{{ item.app_name }}">
          {% if loop.first %}
          <td class="govuk-table__cell" rowspan="{{ item.access_details|length }}" data-is-app-cell="true">{{ item.app_name }}</td>
          {% endif %}
          <td class="govuk-table__cell">{{ detail.environment }}</td>
          <td class="govuk-table__cell">{{ detail.access_level }}</td>
          <td class="govuk-table__cell">
            {% for group in detail.groups %}
              <a class="govuk-link" href="{{ group.group_url }}" target="_blank" rel="noopener noreferrer">{{ group.group_name }}</a>{% if not loop.last %}, {% endif %}
            {% endfor %}
          </td>
        </tr>
            {% endfor %}
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </section>

  <!-- Chart.js Library -->
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
  
  <script>
    // Search functionality - filter individual rows and adjust rowspan
    document.getElementById('access-search').addEventListener('input', function() {
      const query = this.value.toLowerCase().trim();
      const terms = query.split(/\s+/);
      const rows = document.querySelectorAll('#access-table-body tr');
      
      let currentAppRows = [];
      let currentAppName = null;
      
      rows.forEach((row) => {
        // Check if this row has app name cell (first row of an app group)
        const hasAppName = row.cells[0].hasAttribute('rowspan');
        
        if (hasAppName) {
          // Process previous app group
          if (currentAppRows.length > 0) {
            processAppGroup(currentAppRows, currentAppName);
          }
          
          // Start new app group - store app name info
          currentAppName = row.cells[0].cloneNode(true);
          currentAppRows = [row];
        } else {
          // This is a continuation row for the same app
          currentAppRows.push(row);
        }
      });
      
      // Process last app group
      if (currentAppRows.length > 0) {
        processAppGroup(currentAppRows, currentAppName);
      }
      
      function processAppGroup(appRows, appNameCell) {
        // Check which rows match the search
        const matchingRows = appRows.filter(row => {
          // Get individual cell values (excluding app name which may have rowspan)
          const cells = row.cells;
          const cellIndex = cells[0].hasAttribute('rowspan') ? 0 : -1;
          
          const appName = (cellIndex === 0 ? cells[0] : appNameCell).textContent.toLowerCase();
          const environment = cells[cellIndex + 1].textContent.toLowerCase();
          const accessLevel = cells[cellIndex + 2].textContent.toLowerCase();
          const groupName = cells[cellIndex + 3].textContent.toLowerCase();
          
          // Check if all search terms match
          return terms.every(term => {
            // For group names, require exact match
            if (groupName === term) {
              return true;
            }
            // For environment, use word boundary matching to prevent "production" matching "preproduction"
            const envMatch = new RegExp('\\b' + term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b').test(environment);
            // For other fields, use contains matching
            return appName.includes(term) || 
                   envMatch || 
                   accessLevel.includes(term);
          });
        });
        
        if (matchingRows.length === 0) {
          // Hide all rows for this app
          appRows.forEach(r => r.style.display = 'none');
        } else {
          // Show only matching rows
          appRows.forEach(r => r.style.display = 'none');
          matchingRows.forEach(r => r.style.display = '');
          
          // Update the first visible row to have the app name cell with correct rowspan
          const firstVisibleRow = matchingRows[0];
          
          if (firstVisibleRow.cells[0].hasAttribute('rowspan')) {
            firstVisibleRow.cells[0].setAttribute('rowspan', matchingRows.length);
          } else {
            const newAppNameCell = appNameCell.cloneNode(true);
            newAppNameCell.setAttribute('rowspan', matchingRows.length);
            firstVisibleRow.insertBefore(newAppNameCell, firstVisibleRow.firstChild);
          }
        }
      }
    });

    // Chart.js visualization
    const ctx = document.getElementById('roleUsageChart').getContext('2d');
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: {{ role_counts.keys() | list | tojson }},
        datasets: [{
          label: 'Number of Environments',
          data: {{ role_counts.values() | list | tojson }},
          backgroundColor: [
            '#1d70b8', // GOV.UK blue
            '#d4351c', // GOV.UK red
            '#00703c', // GOV.UK green
            '#f47738', // GOV.UK orange
            '#5694ca', // GOV.UK light blue
            '#912b88', // GOV.UK purple
            '#ffdd00', // GOV.UK yellow
            '#b1b4b6'  // GOV.UK grey
          ],
          borderColor: '#ffffff',
          borderWidth: 1
        }]
      },
      options: {
        responsive: true,
        maintainAspectRatio: true,
        indexAxis: 'y', // This makes it horizontal
        plugins: {
          legend: {
            display: false
          },
          title: {
            display: false
          }
        },
        scales: {
          x: {
            beginAtZero: true,
            ticks: {
              stepSize: 1
            },
            title: {
              display: true,
              text: 'Count'
            }
          },
          y: {
            title: {
              display: true,
              text: 'Access Role'
            }
          }
        }
      }
    });
  </script>
  
  {% endblock %}